version: '3.8'

services:
  kafka1:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - ./config/kraft/server1.properties:/etc/kafka/kafka.properties
    command: >
      bash -c "kafka-storage format -t $$(kafka-storage random-uuid) -c /etc/kafka/kafka.properties &&
               kafka-server-start /etc/kafka/kafka.properties"

  kafka2:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka2
    hostname: kafka2
    ports:
      - "9094:9092"
      - "9095:9093"
    volumes:
      - ./config/kraft/server2.properties:/etc/kafka/kafka.properties
    command: >
      bash -c "kafka-storage format -t $$(kafka-storage random-uuid) -c /etc/kafka/kafka.properties &&
               kafka-server-start /etc/kafka/kafka.properties"

  kafka3:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka3
    hostname: kafka3
    ports:
      - "9096:9092"
      - "9097:9093"
    volumes:
      - ./config/kraft/server3.properties:/etc/kafka/kafka.properties
    command: >
      bash -c "kafka-storage format -t $$(kafka-storage random-uuid) -c /etc/kafka/kafka.properties &&
               kafka-server-start /etc/kafka/kafka.properties"
